#pragma once
#include <string>
#include <vector>

#define FILELOCATION "/Documents/todo.txt" //at ~/
#define LINESEPARATOR ";"

struct nameValue{
    std::string name;
    int value;
};

std::vector<int> errorsCaught;
std::string lastInputLine = "";

std::vector<nameValue> dayNameList = {
    //English
    { "First",  1   },
    { "Second", 2   },
    { "Third",  3   },
    { "Fourth", 4   },
    { "Fifth",  5   },
    { "Sixth",  6   },
    { "Seventh",7   },    
    { "Eighth", 8   }, 
    { "Ninth",  9   }, 
    { "Tenth",  10  }, 
    { "Eleventh",   11  },
    { "Twelfth",    12  },
    { "Thirteenth", 13  },
    { "Fourteenth", 14  },
    { "Fifteenth",  15  },
    { "Sixteenth",  16  },
    { "Seventeenth",17  },
    { "Eighteenth", 18  },
    { "Nineteenth", 19  },
    { "Twentieth",  20  },
    { "Twenty-first",   21  },
    { "Twenty-second",  22  },
    { "Twenty-third",   23  },
    { "Twenty-fourth",  24  },
    { "Twenty-fifth",   25  },
    { "Twenty-sixth",   26  },
    { "Twenty-seventh", 27  },
    { "Twenty-eighth",  28  },
    { "Twenty-ninth",   29  },
    { "Thirtieth",      30  },
    { "Thirty-first",   31  },

    { "1.",   1 },
    { "2.",   2 },
    { "3.",   3 },
    { "4.",   4 },
    { "5.",   5 },
    { "6.",   6 },
    { "7.",   7 },
    { "8.",   8 },
    { "9.",   9 },
    { "10.", 10 },
    { "11.", 11 },
    { "12.", 12 },
    { "13.", 13 },
    { "14.", 14 },
    { "15.", 15 },
    { "16.", 16 },
    { "17.", 17 },
    { "18.", 18 },
    { "19.", 19 },
    { "20.", 20 },
    { "21.", 21 },
    { "22.", 22 },
    { "23.", 23 },
    { "24.", 24 },
    { "25.", 25 },
    { "26.", 26 },
    { "27.", 27 },
    { "28.", 28 },
    { "29.", 29 },
    { "30.", 30 },
    { "31.", 31 },

    //Hungarian
    { "elseje",     1 },
    { "másodika",   2 },
    { "harmadika",  3 },
    { "negyedike",  4 },
    { "ötödike",    5 },
    { "hatodika",   6 },
    { "hetedike",   7 },
    { "nyolcadika", 7 },
    { "kilencedike",9 },
    { "tizedike",   10 },
    { "tizen-egyedike",   11 },
    { "tizen-kettedike",  12 },
    { "tizen-harmadika",  13 },
    { "tizen-negyedike",  14 },
    { "tizen-ötödike",    15 },
    { "tizen-hatodika",   16 },
    { "tizen-hetedike",   17 },
    { "tizen-nyolcadika", 17 },
    { "tizen-kilencedike",19 },
    { "huszadika",       20 },
    { "huszon-egyedike",     21 },
    { "huszon-kettedike",    22 },
    { "huszon-harmadika",    23 },
    { "huszon-negyedike",    24 },
    { "huszon-ötödike",      25 },
    { "huszon-hatodika",     26 },
    { "huszon-hetedike",     27 },
    { "huszon-nyolcadika",   27 },
    { "huszon-kilencedike",  29 },
    { "harmincadika",    30 },
    { "harminc-egyedike", 31 },

    { "tizenegyedike",   11 },
    { "tizenkettedike",  12 },
    { "tizenharmadika",  13 },
    { "tizennegyedike",  14 },
    { "tizenötödike",    15 },
    { "tizenhatodika",   16 },
    { "tizenhetedike",   17 },
    { "tizennyolcadika", 17 },
    { "tizenkilencedike",19 },
    { "huszonegyedike",     21 },
    { "huszonkettedike",    22 },
    { "huszonharmadika",    23 },
    { "huszonnegyedike",    24 },
    { "huszonötödike",      25 },
    { "huszonhatodika",     26 },
    { "huszonhetedike",     27 },
    { "huszonnyolcadika",   27 },
    { "huszonkilencedike",  29 },
    { "harmincegyedike", 31 },

    { "1.-e",   1 },
    { "2.-a",   2 },
    { "3.-a",   3 },
    { "4.-e",   4 },
    { "5.-e",   5 },
    { "6.-a",   6 },
    { "7.-e",   7 },
    { "8.-a",   8 },
    { "9.-e",   9 },
    { "10.-e", 10 },
    { "11.-e", 11 },
    { "12.-e", 12 },
    { "13.-a", 13 },
    { "14.-e", 14 },
    { "15.-e", 15 },
    { "16.-a", 16 },
    { "17.-e", 17 },
    { "18.-a", 18 },
    { "19.-e", 19 },
    { "20.-a", 20 },
    { "21.-e", 21 },
    { "22.-e", 22 },
    { "23.-a", 23 },
    { "24.-e", 24 },
    { "25.-e", 25 },
    { "26.-a", 26 },
    { "27.-e", 27 },
    { "28.-a", 28 },
    { "29.-e", 29 },
    { "30.-a", 30 },
    { "31.-e", 31 }
};

std::vector<nameValue> monthNameList = {
    //English
    {"january", 1},
    {"february", 2},
    {"march", 3},
    {"april", 4},
    {"may", 5},
    {"june", 6},
    {"july", 7},
    {"august", 8},
    {"september", 9},
    {"october",10},
    {"november",11},
    {"december",12},

    {"jan", 1},
    {"feb", 2},
    {"febr", 2},
    {"mar", 3},
    {"apr", 4},
    {"may", 5},
    {"jun", 6},
    {"jul", 7},
    {"aug", 8},
    {"sep", 9},
    {"sept", 9},
    {"oct",10},
    {"nov",11},
    {"dec",12},

    //Hungarian
    {"január", 1},
    {"február", 2},
    {"március", 3},
    {"április", 4},
    {"május", 5},
    {"június", 6},
    {"július", 7},
    {"augusztus", 8},
    {"szeptember", 9},
    {"octóber",10},
    {"november",11},
    {"december",12},

    {"jan", 1},
    {"feb", 2},
    {"febr", 2},
    {"már", 3},
    {"ápr", 4},
    {"máj", 5},
    {"jún", 6},
    {"júl", 7},
    {"aug", 8},
    {"szep", 9},
    {"szept", 9},
    {"oct",10},
    {"nov",11},
    {"dec",12}
};